name: icon
favicon: null
layout_spectrum: 0.522743477486074
typography_spectrum: 0.999916106229648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090909'
    - '#a0d9ff'
    - '#7f7c69'
    - '#324460'
  brandStrength: 0.47280017635785043
  lightness: 0.6358660615514964
  saturation: 0.2794089268427342
  rhythmicContrast: 0.7208605085033923
purpose: []
